name: driver
description: Spelcabs Driver Application for accepting rides.

publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.8
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  
  # Location & Maps
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  google_maps_place_picker_mb: ^3.1.2
  location: ^5.0.3
  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.4.2

  flutter_email_sender: ^6.0.3
  map_launcher: ^3.5.0
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # HTTP & APIs
  googleapis_auth: ^1.6.0
  
  # UI Components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  bottom_picker: ^2.8.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.1.0
  badges: ^3.1.2
  photo_view: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  
  # State Management
  get: ^4.6.6
  provider: ^6.1.2
  
  # Storage & Preferences
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  
  # Utils
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  country_code_picker: ^3.0.0
  clipboard: ^0.1.3
#  flutter_email_sender: ^7.0.0

  # Media - Updated versions
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.3
  video_player: ^2.9.2
  
  # Payment - Updated versions
  flutter_stripe: ^10.2.0
  razorpay_flutter: ^1.4.0
  # flutter_paypal_native: ^2.1.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  webview_flutter: ^4.13.0
  worker_manager: ^7.2.6
  permission_handler: ^12.0.1
  geolocator: ^10.0.1

  http: any
  dio: any
  rxdart: any
dependency_overrides:

#  fluttertoast: ^8.2.8
  webview_flutter: ^4.8.0
  http: ^1.2.2
  js: ^0.6.7
  web: ^0.5.1
  # Add these overrides to handle conflicts
  # video_player_android: ^2.7.5
  # video_player_platform_interface: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/midtrans.png
    - assets/images/xendit.png
    - assets/images/orangepay.png
    - assets/icons/
    - assets/audio/
    - assets/